from enum import Enum

class ResponseSignal(str, Enum):
    FILE_TYPE_NOT_ALLOWED = "FILE_TYPE_NOT_ALLOWED"
    FILE_SIZE_EXCEEDED = "FILE_SIZE_EXCEEDED"
    FILE_UPLOADED_SUCCESS = "FILE_UPLOADED_SUCCESS"
    FILE_UPLOAD_FAILED = "FILE_UPLOAD_FAILED"
    FILE_VALID = "FILE_VALID"
    FILE_INVALID = "FILE_INVALID"
    PROCESSING_FAILED = "PROCESSING_FAILED"
    PROECSSIGN_SUCCESS = "PROCESSING_SUCCESS"
    NO_FILES_FOUND = "NO_FILES_FOUND"
    FILE_ID_ERROR = "FILE_ID_ERROR"
    FILE_NOT_FOUND = "FILE_NOT_FOUND"
    PROJECT_NOT_FOUND = "PROJECT_NOT_FOUND"
    FAILED_TO_INSERT = "FAILED_TO_INSERT"
    INSERT_SUCCESS = "INSERT_SUCCESS"
    VECTOR_DB_SEARCH_SUCCESS = "VECTOR_DB_SEARCH_SUCCESS"
    VECTOR_DB_SEARCH_FAILED = "VECTOR_DB_SEARCH_FAILED"